spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: **
    password: **
    url: **
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10

    #   redis
    redis:
      port: 6379
      host: **
      password: **



server:
  #  端口号
  port: 777
